/**
 * L2 Content Checker
 *
 * Validates content quality of SDLC stage documentation beyond
 * mere file existence (L1). Detects placeholders, checks minimum
 * content length, and validates required artifacts per stage.
 *
 * Fixes BUG-011: Compliance false positive on placeholder docs.
 *
 * @module sdlc/compliance/content-checker
 * @version 1.0.0
 * @date 2026-03-03
 * @status ACTIVE - Sprint 73
 * @authority Sprint 73 Plan, BUG-011
 * @stage 04 - BUILD
 * @sdlc SDLC Framework 6.1.1
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import type { ProjectTier } from "../scaffold/types.js";

// ============================================================================
// Types
// ============================================================================

export interface ContentIssue {
  type: "placeholder" | "insufficient_content" | "missing_artifact";
  severity: "error" | "warning";
  message: string;
  file?: string;
  stage?: string;
}

export interface L2Result {
  score: number;
  totalChecks: number;
  passedChecks: number;
  issues: ContentIssue[];
  stageResults: StageContentResult[];
}

export interface StageContentResult {
  stage: string;
  hasRealContent: boolean;
  contentScore: number;
  totalLines: number;
  placeholdersFound: string[];
  artifactsFound: string[];
  artifactsMissing: string[];
}

// ============================================================================
// Placeholder Detection Patterns
// ============================================================================

const PLACEHOLDER_PATTERNS: RegExp[] = [
  /TODO:\s*Add/i,
  /\bTBD\b/,
  /<!--\s*Add\s+stage-specific/i,
  /\bPending\b.*\bTBD\b/,
  /\[\s*\]\s*TODO/,
  /Generated by EndiorBot/i,
];

/**
 * Check if a line matches any placeholder pattern.
 */
export function isPlaceholderLine(line: string): boolean {
  return PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(line));
}

/**
 * Count placeholder lines in content.
 */
export function countPlaceholders(content: string): string[] {
  const lines = content.split("\n");
  const found: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && isPlaceholderLine(trimmed)) {
      found.push(trimmed);
    }
  }
  return found;
}

// ============================================================================
// Stage Content Requirements
// ============================================================================

/**
 * Required artifacts per stage for STANDARD+ tiers.
 * File patterns are checked with simple name matching.
 */
export const STAGE_CONTENT_REQUIREMENTS: Record<string, StageRequirements> = {
  "00-foundation": {
    minContentLines: 20,
    requiredArtifacts: ["problem-statement.md", "business-case.md"],
    optionalArtifacts: ["master-plan.md", "product-vision*.md"],
  },
  "01-planning": {
    minContentLines: 15,
    requiredArtifacts: ["requirements.md"],
    optionalArtifacts: ["user-stories.md", "roadmap.md"],
  },
  "02-design": {
    minContentLines: 15,
    requiredArtifacts: [],
    optionalArtifacts: ["architecture.md", "api-spec.yaml"],
    requiredSubdirs: ["01-ADRs"],
  },
  "03-integrate": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["integration-plan.md", "contracts.md"],
  },
  "04-build": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["sprints/*.md"],
    requiredSubdirs: ["sprints"],
  },
  "05-test": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["test-plan.md"],
    requiredSubdirs: ["test-plans"],
  },
  "06-deploy": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["deploy-guide.md", "runbook.md"],
  },
  "07-operate": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["monitoring.md", "sla.md"],
  },
  "08-collaborate": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["contributing.md", "team-agreements.md"],
  },
  "09-govern": {
    minContentLines: 10,
    requiredArtifacts: [],
    optionalArtifacts: ["governance.md", "audit-log.md"],
  },
  "10-archive": {
    minContentLines: 10,
    requiredArtifacts: ["archive-checklist.md"],
    optionalArtifacts: ["lessons-learned.md", "project-close-report.md"],
  },
};

interface StageRequirements {
  minContentLines: number;
  requiredArtifacts: string[];
  optionalArtifacts: string[];
  requiredSubdirs?: string[];
}

// ============================================================================
// Content Analysis
// ============================================================================

/**
 * Count meaningful content lines (non-empty, non-placeholder, non-header-only).
 */
export function countContentLines(content: string): number {
  const lines = content.split("\n");
  let count = 0;
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("---")) continue;
    if (isPlaceholderLine(trimmed)) continue;
    count++;
  }
  return count;
}

/**
 * Get all markdown/yaml files in a stage directory (recursive, 2 levels).
 */
function getStageFiles(stagePath: string): string[] {
  const files: string[] = [];
  if (!existsSync(stagePath)) return files;

  try {
    const entries = readdirSync(stagePath, { withFileTypes: true });
    for (const entry of entries) {
      const entryPath = join(stagePath, entry.name);
      if (entry.isFile() && /\.(md|yaml|yml|json)$/i.test(entry.name)) {
        files.push(entry.name);
      } else if (entry.isDirectory()) {
        // Go one level deeper
        try {
          const subEntries = readdirSync(entryPath, { withFileTypes: true });
          for (const sub of subEntries) {
            if (sub.isFile() && /\.(md|yaml|yml|json)$/i.test(sub.name)) {
              files.push(join(entry.name, sub.name));
            }
          }
        } catch {
          // Permission or access error
        }
      }
    }
  } catch {
    // Permission or access error
  }
  return files;
}

/**
 * Check if a required artifact exists in the stage files.
 * Supports simple wildcard patterns (* at end).
 */
function artifactExists(required: string, stageFiles: string[]): boolean {
  if (required.includes("*")) {
    const prefix = required.replace(/\*.*$/, "");
    return stageFiles.some((f) => f.startsWith(prefix));
  }
  return stageFiles.some((f) => f === required || f.endsWith(`/${required}`));
}

// ============================================================================
// Stage Content Check
// ============================================================================

/**
 * Check content quality for a single stage.
 */
export function checkStageContent(
  projectPath: string,
  stage: string,
): StageContentResult {
  const stagePath = join(projectPath, "docs", stage);
  const requirements = STAGE_CONTENT_REQUIREMENTS[stage];

  const result: StageContentResult = {
    stage,
    hasRealContent: false,
    contentScore: 0,
    totalLines: 0,
    placeholdersFound: [],
    artifactsFound: [],
    artifactsMissing: [],
  };

  if (!existsSync(stagePath)) return result;

  // Get all files in stage
  const stageFiles = getStageFiles(stagePath);

  // Read and analyze all content
  let totalContentLines = 0;
  const allPlaceholders: string[] = [];

  for (const file of stageFiles) {
    const filePath = join(stagePath, file);
    try {
      const stat = statSync(filePath);
      if (!stat.isFile()) continue;
      const content = readFileSync(filePath, "utf-8");
      totalContentLines += countContentLines(content);
      allPlaceholders.push(...countPlaceholders(content));
    } catch {
      // Skip unreadable files
    }
  }

  result.totalLines = totalContentLines;
  result.placeholdersFound = allPlaceholders;

  if (!requirements) {
    // Unknown stage — score based on content alone
    result.hasRealContent = totalContentLines > 10 && allPlaceholders.length === 0;
    result.contentScore = totalContentLines > 10 ? 100 : 0;
    return result;
  }

  // Check required artifacts
  for (const artifact of requirements.requiredArtifacts) {
    if (artifactExists(artifact, stageFiles)) {
      result.artifactsFound.push(artifact);
    } else {
      result.artifactsMissing.push(artifact);
    }
  }

  // Check required subdirs
  if (requirements.requiredSubdirs) {
    for (const subdir of requirements.requiredSubdirs) {
      const subdirPath = join(stagePath, subdir);
      if (existsSync(subdirPath)) {
        result.artifactsFound.push(`${subdir}/`);
      } else {
        result.artifactsMissing.push(`${subdir}/`);
      }
    }
  }

  // Calculate score (4 factors, each 25%)
  const factors: number[] = [];

  // Factor 1: Content volume (min lines met?)
  const lineFactor = Math.min(totalContentLines / requirements.minContentLines, 1.0);
  factors.push(lineFactor);

  // Factor 2: No placeholders
  const placeholderRatio = stageFiles.length > 0
    ? Math.max(0, 1 - allPlaceholders.length / Math.max(stageFiles.length, 1))
    : 0;
  factors.push(placeholderRatio);

  // Factor 3: Required artifacts present
  const requiredTotal = requirements.requiredArtifacts.length + (requirements.requiredSubdirs?.length ?? 0);
  const artifactFactor = requiredTotal > 0
    ? (requiredTotal - result.artifactsMissing.length) / requiredTotal
    : 1.0; // No required artifacts = full score
  factors.push(artifactFactor);

  // Factor 4: File count beyond just README.md
  const meaningfulFiles = stageFiles.filter((f) => f.toLowerCase() !== "readme.md");
  const fileFactor = meaningfulFiles.length > 0 ? 1.0 : 0.0;
  factors.push(fileFactor);

  result.contentScore = Math.round(
    factors.reduce((sum, f) => sum + f, 0) / factors.length * 100,
  );
  result.hasRealContent = result.contentScore >= 50;

  return result;
}

// ============================================================================
// Full L2 Check
// ============================================================================

/**
 * Run L2 content quality checks across all stages.
 */
export function checkL2Compliance(
  projectPath: string,
  stages: string[],
  _tier: ProjectTier,
): L2Result {
  const issues: ContentIssue[] = [];
  const stageResults: StageContentResult[] = [];

  for (const stage of stages) {
    const result = checkStageContent(projectPath, stage);
    stageResults.push(result);

    // Report placeholders
    if (result.placeholdersFound.length > 0) {
      issues.push({
        type: "placeholder",
        severity: "warning",
        message: `Stage ${stage}: ${result.placeholdersFound.length} placeholder(s) found`,
        stage,
      });
    }

    // Report insufficient content
    const requirements = STAGE_CONTENT_REQUIREMENTS[stage];
    if (requirements && result.totalLines < requirements.minContentLines) {
      issues.push({
        type: "insufficient_content",
        severity: "warning",
        message: `Stage ${stage}: ${result.totalLines} content lines (minimum: ${requirements.minContentLines})`,
        stage,
      });
    }

    // Report missing artifacts
    for (const missing of result.artifactsMissing) {
      issues.push({
        type: "missing_artifact",
        severity: "warning",
        message: `Stage ${stage}: missing required artifact '${missing}'`,
        stage,
        file: missing,
      });
    }
  }

  // Calculate overall L2 score
  const totalChecks = stageResults.length;
  const passedChecks = stageResults.filter((r) => r.hasRealContent).length;
  const score = totalChecks > 0 ? Math.round((passedChecks / totalChecks) * 100) : 0;

  return {
    score,
    totalChecks,
    passedChecks,
    issues,
    stageResults,
  };
}
