/**
 * Plugin Manifest Tests
 *
 * Unit tests for .claude-plugin/plugin.json generation (ADR-056, Sprint 151).
 *
 * @module tests/sdlc/scaffold/plugin-manifest
 * @version 1.0.0
 * @date 2026-05-27
 * @status ACTIVE - Sprint 151
 * @sdlc SDLC Framework 6.3.1
 */

import { describe, it, expect } from "vitest";
import {
  generatePluginManifest,
  generateCommandsReadme,
  generateSkillsReadme,
} from "../../../src/sdlc/scaffold/templates/plugin-manifest.js";
import type { ProjectConfig } from "../../../src/sdlc/scaffold/types.js";

const testProject: ProjectConfig = {
  id: "test-project",
  name: "Test Project",
  description: "A test project for unit testing",
  tier: "STANDARD",
  frameworkVersion: "6.3.1",
};

// ============================================================================
// generatePluginManifest Tests
// ============================================================================

describe("generatePluginManifest", () => {
  it("should return valid JSON with all Base profile fields", () => {
    const content = generatePluginManifest(testProject);
    const manifest = JSON.parse(content) as Record<string, unknown>;

    expect(manifest.schema_profile).toBe("base");
    expect(manifest.schema_version).toBe("0.1.0");
    expect(manifest.runtime_compat).toBe(">=0.1.0 <1.0.0");
    expect(manifest.name).toBe("test-project");
    expect(manifest.version).toBe("0.1.0");
    expect(manifest.description).toBe("A test project for unit testing");
    expect(manifest.required_context).toEqual({
      filesystem_paths: ["repo"],
      env_vars: [],
      secrets_required: false,
    });
  });

  it("should always use schema_profile base", () => {
    const content = generatePluginManifest(testProject);
    const manifest = JSON.parse(content) as Record<string, unknown>;
    expect(manifest.schema_profile).toBe("base");
  });

  it("should never include Governed fields", () => {
    const content = generatePluginManifest(testProject);
    const manifest = JSON.parse(content) as Record<string, unknown>;

    expect(manifest.policy).toBeUndefined();
    expect(manifest.trust).toBeUndefined();
    expect(manifest.permissions).toBeUndefined();
    expect(manifest.required_evidence).toBeUndefined();
  });

  it("should use project description when available", () => {
    const project: ProjectConfig = {
      ...testProject,
      description: "Custom desc",
    };
    const content = generatePluginManifest(project);
    const manifest = JSON.parse(content) as Record<string, unknown>;
    expect(manifest.description).toBe("Custom desc");
  });

  it("should fallback description when project.description is empty", () => {
    const project: ProjectConfig = {
      ...testProject,
      description: "",
    };
    const content = generatePluginManifest(project);
    const manifest = JSON.parse(content) as Record<string, unknown>;
    expect(manifest.description).toBe("Test Project — Generated by EndiorBot");
  });

  it("should normalize name to kebab-case via project.id", () => {
    const project: ProjectConfig = {
      ...testProject,
      id: "my-awesome-project",
      name: "My Awesome Project",
    };
    const content = generatePluginManifest(project);
    const manifest = JSON.parse(content) as Record<string, unknown>;
    expect(manifest.name).toBe("my-awesome-project");
  });

  it("should end with newline", () => {
    const content = generatePluginManifest(testProject);
    expect(content.endsWith("\n")).toBe(true);
  });
});

// ============================================================================
// generateCommandsReadme Tests
// ============================================================================

describe("generateCommandsReadme", () => {
  it("should include project name", () => {
    const content = generateCommandsReadme(testProject);
    expect(content).toContain("Test Project");
  });

  it("should include command format example", () => {
    const content = generateCommandsReadme(testProject);
    expect(content).toContain("name: my-command");
    expect(content).toContain("# /my-command");
  });

  it("should be valid markdown", () => {
    const content = generateCommandsReadme(testProject);
    expect(content.startsWith("# Commands")).toBe(true);
  });
});

// ============================================================================
// generateSkillsReadme Tests
// ============================================================================

describe("generateSkillsReadme", () => {
  it("should include project name", () => {
    const content = generateSkillsReadme(testProject);
    expect(content).toContain("Test Project");
  });

  it("should include skill format example", () => {
    const content = generateSkillsReadme(testProject);
    expect(content).toContain("name: code-review");
    expect(content).toContain("SKILL.md");
  });

  it("should be valid markdown", () => {
    const content = generateSkillsReadme(testProject);
    expect(content.startsWith("# Skills")).toBe(true);
  });
});
