/**
 * CLAUDE.md Generator
 *
 * Generates CLAUDE.md content for Claude Code integration.
 *
 * @module sdlc/scaffold/templates/claude-md
 * @version 1.1.0
 * @date 2026-03-05
 * @status ACTIVE - Sprint 79
 */

import type { ProjectConfig, ProjectTier } from "../types.js";
import type { ProjectSnapshot } from "../../compliance/fix-types.js";

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate CLAUDE.md content.
 * When snapshot is provided, commands section uses detected package manager + scripts.
 */
export function generateClaudeMd(project: ProjectConfig, snapshot?: ProjectSnapshot): string {
  const tierSection = getTierSection(project.tier);
  const commandsSection = getCommandsSection(snapshot);
  const invariantsSection = getInvariantsSection();
  const contextFilesSection = getContextFilesSection(project.tier);

  return `# CLAUDE.md - ${project.name}

## Overview

${project.description || `${project.name} project managed with EndiorBot SDLC Framework.`}

**Tier:** ${project.tier}
**Framework:** SDLC ${project.frameworkVersion}

---

${invariantsSection}

---

## Configuration Files

| File | Purpose |
|------|---------|
| \`.sdlc-config.json\` | SDLC framework configuration |
| \`IDENTITY.md\` | Project identity and capabilities |
| \`AGENTS.md\` | AI agent guidelines |
| \`CLAUDE.md\` | Claude-specific integration (this file) |

---

${tierSection}

---

${commandsSection}

---

## Code Style

### TypeScript
- Use strict mode
- Explicit types (no \`any\`)
- Prefer \`const\` over \`let\`
- Use template literals
- Document public APIs with JSDoc

### Commit Messages

Follow conventional commits:
\`\`\`
feat(scope): add feature description
fix(scope): fix bug description
docs(scope): update documentation
refactor(scope): refactor code
test(scope): add tests
\`\`\`

---

## SDLC Integration

### Gate Awareness
Before major changes, check gate requirements:
\`\`\`bash
./endiorbot.mjs gate status
./endiorbot.mjs gate recommend G2
\`\`\`

### Quality Assurance
Monitor vibecoding index to maintain code quality:
\`\`\`bash
./endiorbot.mjs vibecoding check
\`\`\`

Target: Vibecoding Index < 40 (Green zone)

${contextFilesSection}

---

*CLAUDE.md generated by EndiorBot*
*SDLC Framework v${project.frameworkVersion}*
`;
}

// ============================================================================
// Section Generators
// ============================================================================

/**
 * Get 4 Non-Negotiable Invariants section.
 */
function getInvariantsSection(): string {
  return `<!-- ENDIORBOT:MANAGED:START -->
## 4 Non-Negotiable Invariants

\`\`\`
1. THIN CLIENT PATTERN
   Claude Code commands = wrappers that call ./endiorbot.mjs
   NO business logic in .md files
   Gate checks, vibecoding, multi-model → all in EndiorBot core

2. STDIN JSON FOR HOOKS
   Hooks receive JSON via stdin, NOT positional arguments
   Always parse with jq: cat /dev/stdin | jq -r '.tool_name'
   Test: echo '{"tool_name":"Edit","file_path":"test.ts"}' | ./hook.sh

3. ENDIORBOT SOUL = GOVERNANCE, CLAUDE CODE = EXECUTION
   EndiorBot SOUL decides WHAT to build (PM, requirements, gates)
   Claude Code executes HOW to build (Architect, Coder, Reviewer)
   No PM agent in Claude Code (prevents orchestration conflict)

4. DEFAULT MODEL = SONNET
   Opus only for explicit architecture decisions
   Commands use model: sonnet unless specified
   Budget guard: track /cost regularly
\`\`\`
<!-- ENDIORBOT:MANAGED:END -->`;
}

/**
 * Get tier-specific section.
 */
function getTierSection(tier: ProjectTier): string {
  const sections: Record<ProjectTier, string> = {
    LITE: `## Tier: LITE

**Features:**
- 2 AI agents (assistant, coder)
- 4 lifecycle stages (foundation, planning, design, build)
- Basic gate requirements
- Solo developer workflow`,

    STANDARD: `## Tier: STANDARD

**Features:**
- 5+ AI agents (assistant, pm, pjm, coder, reviewer)
- 7 lifecycle stages
- Sprint gates (G-Sprint, G-Sprint-Close)
- Team collaboration support
- Soft enforcement mode`,

    PROFESSIONAL: `## Tier: PROFESSIONAL

**Features:**
- 10+ AI agents including researcher, architect, tester
- 10 lifecycle stages
- Full gate pipeline (G0.1 → G4)
- Hard enforcement mode
- Code review requirements`,

    ENTERPRISE: `## Tier: ENTERPRISE

**Features:**
- 12 AI agents including DevOps
- Full 11-stage lifecycle
- Executive gates (G0.1, G4)
- Audit trail required
- Maximum governance`,
  };

  return sections[tier];
}

/** Priority-ordered script keys to include in commands section. */
const SCRIPT_PRIORITY = ["dev", "build", "test", "test:unit", "lint", "format", "typecheck", "check"] as const;

/** Fallback commands section when no snapshot available. */
const GENERIC_COMMANDS_SECTION = `## Commands

### Development
\`\`\`bash
pnpm install        # Install dependencies
pnpm build          # Build TypeScript
pnpm dev            # Watch mode
pnpm test           # Run tests
pnpm lint           # Check code style
\`\`\`

### EndiorBot CLI
\`\`\`bash
./endiorbot.mjs --help           # Show help
./endiorbot.mjs start <project>  # Start project
./endiorbot.mjs switch <project> # Switch context
./endiorbot.mjs gate status      # Show gate status
./endiorbot.mjs consult <query>  # Multi-model query
\`\`\`

### Claude Code Integration
\`\`\`bash
# Thin client pattern - CLI wrappers call EndiorBot core
./endiorbot.mjs gate check G3
./endiorbot.mjs consult "Redis vs PostgreSQL for sessions?"
./endiorbot.mjs vibecoding check
\`\`\``;

/**
 * Get commands section.
 * Uses detected package manager and scripts when snapshot is available.
 */
function getCommandsSection(snapshot?: ProjectSnapshot): string {
  if (!snapshot) return GENERIC_COMMANDS_SECTION;

  const pm = snapshot.techStack.packageManager ?? "pnpm";
  const scripts = snapshot.techStack.scripts ?? {};

  // Build dev commands from detected scripts in priority order
  const scriptLines: string[] = [];

  // Install always comes first
  scriptLines.push(`${pm} install        # Install dependencies`);

  for (const key of SCRIPT_PRIORITY) {
    if (scripts[key]) {
      const label = getScriptLabel(key);
      scriptLines.push(`${pm} run ${key.padEnd(12)} # ${label}`);
    }
  }

  if (scriptLines.length <= 1) {
    // No known scripts found — fallback
    return GENERIC_COMMANDS_SECTION;
  }

  return `## Commands

### Development
\`\`\`bash
${scriptLines.join("\n")}
\`\`\`

### EndiorBot CLI
\`\`\`bash
./endiorbot.mjs --help           # Show help
./endiorbot.mjs start <project>  # Start project
./endiorbot.mjs switch <project> # Switch context
./endiorbot.mjs gate status      # Show gate status
./endiorbot.mjs consult <query>  # Multi-model query
\`\`\`

### Claude Code Integration
\`\`\`bash
# Thin client pattern - CLI wrappers call EndiorBot core
./endiorbot.mjs gate check G3
./endiorbot.mjs consult "Redis vs PostgreSQL for sessions?"
./endiorbot.mjs vibecoding check
\`\`\``;
}

/**
 * Get "Context Files" section for STANDARD+ tiers.
 * Points to subdirectory CLAUDE.md files (Sprint 150, ADR-055).
 */
function getContextFilesSection(tier: ProjectTier): string {
  if (tier === "LITE") return "";

  const subdirs: Record<string, string> = {
    src: "Code conventions and patterns",
    tests: "Testing conventions and commands",
    docs: "Documentation standards and SDLC stages",
  };

  const lines = [
    "",
    "## Context Files",
    "",
    "This project uses layered CLAUDE.md files for scoped context:",
  ];

  const tierSubdirs: Record<ProjectTier, string[]> = {
    LITE: [],
    STANDARD: ["src", "tests"],
    PROFESSIONAL: ["src", "docs", "tests"],
    ENTERPRISE: ["src", "docs", "tests"],
  };

  for (const subdir of tierSubdirs[tier]) {
    lines.push(`- \`${subdir}/CLAUDE.md\` — ${subdirs[subdir]}`);
  }

  return lines.join("\n");
}

function getScriptLabel(key: string): string {
  const labels: Record<string, string> = {
    dev: "Watch mode / dev server",
    build: "Build / compile",
    test: "Run tests",
    "test:unit": "Unit tests only",
    lint: "Check code style",
    format: "Format code",
    typecheck: "Type checking only",
    check: "Type check",
  };
  return labels[key] ?? key;
}

// ============================================================================
// Subdirectory CLAUDE.md Generation (Sprint 150, ADR-055)
// ============================================================================

/**
 * Generate a short subdirectory CLAUDE.md scoped to a specific folder.
 * Target: < 100 lines. Includes pointer back to root CLAUDE.md.
 */
export function generateSubdirClaudeMd(
  subdir: string,
  project: ProjectConfig,
  snapshot?: ProjectSnapshot
): string {
  const lines: string[] = [
    `# CLAUDE.md — ${subdir}/`,
    "",
    `> See root \`CLAUDE.md\` for project overview and global conventions.`,
    "",
    `**Project:** ${project.name}  `,
    `**Tier:** ${project.tier}  `,
    `**Scope:** ${subdir}/ directory`,
    "",
    "---",
    "",
  ];

  switch (subdir) {
    case "src": {
      lines.push(...getSrcSection(project, snapshot));
      break;
    }
    case "tests": {
      lines.push(...getTestsSection(project, snapshot));
      break;
    }
    case "docs": {
      lines.push(...getDocsSection(project));
      break;
    }
    default: {
      lines.push(`## ${subdir} Conventions`, "", "Add directory-specific conventions here.");
    }
  }

  lines.push(
    "",
    "---",
    "",
    "*Generated by EndiorBot*  ",
    `*SDLC Framework v${project.frameworkVersion}*`
  );

  return lines.join("\n");
}

function getSrcSection(_project: ProjectConfig, snapshot?: ProjectSnapshot): string[] {
  const lines: string[] = [
    "## Code Conventions",
    "",
    "### Structure",
    "- Keep modules focused (single responsibility).",
    "- Co-locate unit tests next to source files or under a dedicated `tests/` tree.",
    "- Use barrel exports (`index.ts`) for clean public APIs.",
  ];

  if (snapshot?.techStack.language) {
    const lang = snapshot.techStack.language;
    lines.push("", `### ${lang} Patterns`);

    if (lang === "TypeScript" || lang === "JavaScript") {
      lines.push(
        "- Prefer explicit types; avoid `any`.",
        "- Use `const` / `readonly` for immutability.",
        "- Import order: external → internal → relative.",
        "- Use template literals for string interpolation."
      );
    } else if (lang === "Python") {
      lines.push(
        "- Use type hints (PEP 484).",
        "- Import order: stdlib → third-party → local.",
        "- Prefer dataclasses or Pydantic models for structured data."
      );
    } else if (lang === "Go") {
      lines.push(
        "- Group imports: stdlib → external → internal.",
        "- Return errors explicitly; avoid panics in library code.",
        "- Keep interfaces small and consumer-defined."
      );
    } else {
      lines.push(`- Follow ${lang} community style guides.`);
    }

    if (snapshot.techStack.framework) {
      lines.push(`- Framework: ${snapshot.techStack.framework}`);
    }
  } else {
    lines.push(
      "",
      "### General",
      "- Follow the tech-stack style guide used by this project.",
      "- Keep functions small and testable."
    );
  }

  lines.push(
    "",
    "### Imports",
    "- Avoid circular dependencies.",
    "- Prefer absolute imports for cross-module references."
  );

  return lines;
}

function getTestsSection(_project: ProjectConfig, snapshot?: ProjectSnapshot): string[] {
  const pm = snapshot?.techStack.packageManager ?? "pnpm";
  const lang = snapshot?.techStack.language ?? "TypeScript";

  const testCmd = lang === "Python"
    ? "pytest tests/"
    : `${pm} vitest run tests/`;

  const lines: string[] = [
    "## Testing Conventions",
    "",
    "### Commands",
    "```bash",
    `${testCmd}    # Run all tests in this directory`,
    "```",
    "",
    "### Guidelines",
    "- Name tests descriptively: `should <expected behavior> when <condition>`.",
    "- Group related tests with `describe` blocks.",
    "- Test error paths explicitly.",
    "- Reset singleton / module state in `beforeEach`.",
    "- Mock external dependencies; test internal logic directly.",
  ];

  if (lang === "TypeScript" || lang === "JavaScript") {
    lines.push(
      "- Use `vi.fn()` for mocks (Vitest).",
      "- Target: 70%+ coverage for modules under test."
    );
  } else if (lang === "Python") {
    lines.push(
      "- Use `pytest` fixtures for shared setup.",
      "- Target: 70%+ coverage for modules under test."
    );
  }

  lines.push("", "### Files", "- Keep test files next to source or under `tests/` tree.");

  return lines;
}

function getDocsSection(_project: ProjectConfig): string[] {
  return [
    "## Documentation Standards",
    "",
    "### Structure",
    "- Use numbered stage folders (`00-foundation`, `01-planning`, ...).",
    "- Each stage README explains purpose, entry criteria, and exit gates.",
    "",
    "### ADRs",
    "- One ADR per major architectural decision.",
    "- Include YAML frontmatter with `authority` block.",
    "- Reference: `docs/02-design/01-ADRs/`",
    "",
    "### Markdown Style",
    "- Use ATX-style headings (`#`).",
    "- Prefer tables for structured comparisons.",
    "- Link related docs with relative paths.",
    "",
    "### SDLC Stages (this project)",
    ..._project.tier.split("").map(() => "").slice(0, 0), // no-op placeholder to satisfy type check
    ...getTierStageList(_project.tier),
  ];
}

function getTierStageList(tier: ProjectTier): string[] {
  const stages: Record<ProjectTier, string[]> = {
    LITE: ["00-foundation", "01-planning", "02-design", "04-build"],
    STANDARD: [
      "00-foundation", "01-planning", "02-design", "04-build",
      "05-test", "06-deploy", "08-collaborate",
    ],
    PROFESSIONAL: [
      "00-foundation", "01-planning", "02-design", "03-integrate",
      "04-build", "05-test", "06-deploy", "07-operate",
      "08-collaborate", "09-govern",
    ],
    ENTERPRISE: [
      "00-foundation", "01-planning", "02-design", "03-integrate",
      "04-build", "05-test", "06-deploy", "07-operate",
      "08-collaborate", "09-govern", "10-archive",
    ],
  };

  return stages[tier].map((s) => `- \`${s}/\``);
}
