/**
 * CLAUDE.md Generator
 *
 * Generates CLAUDE.md content for Claude Code integration.
 *
 * @module sdlc/scaffold/templates/claude-md
 * @version 1.1.0
 * @date 2026-03-05
 * @status ACTIVE - Sprint 79
 */

import type { ProjectConfig, ProjectTier } from "../types.js";
import type { ProjectSnapshot } from "../../compliance/fix-types.js";

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate CLAUDE.md content.
 * When snapshot is provided, commands section uses detected package manager + scripts.
 */
export function generateClaudeMd(project: ProjectConfig, snapshot?: ProjectSnapshot): string {
  const tierSection = getTierSection(project.tier);
  const commandsSection = getCommandsSection(snapshot);
  const invariantsSection = getInvariantsSection();

  return `# CLAUDE.md - ${project.name}

## Overview

${project.description || `${project.name} project managed with EndiorBot SDLC Framework.`}

**Tier:** ${project.tier}
**Framework:** SDLC 6.1.1

---

${invariantsSection}

---

## Configuration Files

| File | Purpose |
|------|---------|
| \`.sdlc-config.json\` | SDLC framework configuration |
| \`IDENTITY.md\` | Project identity and capabilities |
| \`AGENTS.md\` | AI agent guidelines |
| \`CLAUDE.md\` | Claude-specific integration (this file) |

---

${tierSection}

---

${commandsSection}

---

## Code Style

### TypeScript
- Use strict mode
- Explicit types (no \`any\`)
- Prefer \`const\` over \`let\`
- Use template literals
- Document public APIs with JSDoc

### Commit Messages

Follow conventional commits:
\`\`\`
feat(scope): add feature description
fix(scope): fix bug description
docs(scope): update documentation
refactor(scope): refactor code
test(scope): add tests
\`\`\`

---

## SDLC Integration

### Gate Awareness
Before major changes, check gate requirements:
\`\`\`bash
./endiorbot.mjs gate status
./endiorbot.mjs gate recommend G2
\`\`\`

### Quality Assurance
Monitor vibecoding index to maintain code quality:
\`\`\`bash
./endiorbot.mjs vibecoding check
\`\`\`

Target: Vibecoding Index < 40 (Green zone)

---

*CLAUDE.md generated by EndiorBot*
*SDLC Framework v${project.frameworkVersion}*
`;
}

// ============================================================================
// Section Generators
// ============================================================================

/**
 * Get 4 Non-Negotiable Invariants section.
 */
function getInvariantsSection(): string {
  return `<!-- ENDIORBOT:MANAGED:START -->
## 4 Non-Negotiable Invariants

\`\`\`
1. THIN CLIENT PATTERN
   Claude Code commands = wrappers that call ./endiorbot.mjs
   NO business logic in .md files
   Gate checks, vibecoding, multi-model → all in EndiorBot core

2. STDIN JSON FOR HOOKS
   Hooks receive JSON via stdin, NOT positional arguments
   Always parse with jq: cat /dev/stdin | jq -r '.tool_name'
   Test: echo '{"tool_name":"Edit","file_path":"test.ts"}' | ./hook.sh

3. ENDIORBOT SOUL = GOVERNANCE, CLAUDE CODE = EXECUTION
   EndiorBot SOUL decides WHAT to build (PM, requirements, gates)
   Claude Code executes HOW to build (Architect, Coder, Reviewer)
   No PM agent in Claude Code (prevents orchestration conflict)

4. DEFAULT MODEL = SONNET
   Opus only for explicit architecture decisions
   Commands use model: sonnet unless specified
   Budget guard: track /cost regularly
\`\`\`
<!-- ENDIORBOT:MANAGED:END -->`;
}

/**
 * Get tier-specific section.
 */
function getTierSection(tier: ProjectTier): string {
  const sections: Record<ProjectTier, string> = {
    LITE: `## Tier: LITE

**Features:**
- 2 AI agents (assistant, coder)
- 4 lifecycle stages (foundation, planning, design, build)
- Basic gate requirements
- Solo developer workflow`,

    STANDARD: `## Tier: STANDARD

**Features:**
- 5+ AI agents (assistant, pm, pjm, coder, reviewer)
- 7 lifecycle stages
- Sprint gates (G-Sprint, G-Sprint-Close)
- Team collaboration support
- Soft enforcement mode`,

    PROFESSIONAL: `## Tier: PROFESSIONAL

**Features:**
- 10+ AI agents including researcher, architect, tester
- 10 lifecycle stages
- Full gate pipeline (G0.1 → G4)
- Hard enforcement mode
- Code review requirements`,

    ENTERPRISE: `## Tier: ENTERPRISE

**Features:**
- 12 AI agents including DevOps
- Full 11-stage lifecycle
- Executive gates (G0.1, G4)
- Audit trail required
- Maximum governance`,
  };

  return sections[tier];
}

/** Priority-ordered script keys to include in commands section. */
const SCRIPT_PRIORITY = ["dev", "build", "test", "test:unit", "lint", "format", "typecheck", "check"] as const;

/** Fallback commands section when no snapshot available. */
const GENERIC_COMMANDS_SECTION = `## Commands

### Development
\`\`\`bash
pnpm install        # Install dependencies
pnpm build          # Build TypeScript
pnpm dev            # Watch mode
pnpm test           # Run tests
pnpm lint           # Check code style
\`\`\`

### EndiorBot CLI
\`\`\`bash
./endiorbot.mjs --help           # Show help
./endiorbot.mjs start <project>  # Start project
./endiorbot.mjs switch <project> # Switch context
./endiorbot.mjs gate status      # Show gate status
./endiorbot.mjs consult <query>  # Multi-model query
\`\`\`

### Claude Code Integration
\`\`\`bash
# Thin client pattern - CLI wrappers call EndiorBot core
./endiorbot.mjs gate check G3
./endiorbot.mjs consult "Redis vs PostgreSQL for sessions?"
./endiorbot.mjs vibecoding check
\`\`\``;

/**
 * Get commands section.
 * Uses detected package manager and scripts when snapshot is available.
 */
function getCommandsSection(snapshot?: ProjectSnapshot): string {
  if (!snapshot) return GENERIC_COMMANDS_SECTION;

  const pm = snapshot.techStack.packageManager ?? "pnpm";
  const scripts = snapshot.techStack.scripts ?? {};

  // Build dev commands from detected scripts in priority order
  const scriptLines: string[] = [];

  // Install always comes first
  scriptLines.push(`${pm} install        # Install dependencies`);

  for (const key of SCRIPT_PRIORITY) {
    if (scripts[key]) {
      const label = getScriptLabel(key);
      scriptLines.push(`${pm} run ${key.padEnd(12)} # ${label}`);
    }
  }

  if (scriptLines.length <= 1) {
    // No known scripts found — fallback
    return GENERIC_COMMANDS_SECTION;
  }

  return `## Commands

### Development
\`\`\`bash
${scriptLines.join("\n")}
\`\`\`

### EndiorBot CLI
\`\`\`bash
./endiorbot.mjs --help           # Show help
./endiorbot.mjs start <project>  # Start project
./endiorbot.mjs switch <project> # Switch context
./endiorbot.mjs gate status      # Show gate status
./endiorbot.mjs consult <query>  # Multi-model query
\`\`\`

### Claude Code Integration
\`\`\`bash
# Thin client pattern - CLI wrappers call EndiorBot core
./endiorbot.mjs gate check G3
./endiorbot.mjs consult "Redis vs PostgreSQL for sessions?"
./endiorbot.mjs vibecoding check
\`\`\``;
}

function getScriptLabel(key: string): string {
  const labels: Record<string, string> = {
    dev: "Watch mode / dev server",
    build: "Build / compile",
    test: "Run tests",
    "test:unit": "Unit tests only",
    lint: "Check code style",
    format: "Format code",
    typecheck: "Type checking only",
    check: "Type check",
  };
  return labels[key] ?? key;
}
