/**
 * IDENTITY.md Generator
 *
 * Generates IDENTITY.md content for project identity.
 *
 * @module sdlc/scaffold/templates/identity-md
 * @version 1.0.0
 * @date 2026-03-01
 * @status ACTIVE - Sprint 61
 */

import type { ProjectConfig } from "../types.js";

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate IDENTITY.md content.
 */
export function generateIdentityMd(project: ProjectConfig): string {
  return `# ${project.name} - Project Identity

## Core Identity

**Project:** ${project.name}
**ID:** ${project.id}
**Tier:** ${project.tier}
**Framework:** SDLC ${project.frameworkVersion}

---

## Description

${project.description || `${project.name} is a project managed with the SDLC Framework.`}

---

## Purpose

<!-- Define the core purpose of this project -->
> What problem does this project solve?

TODO: Add project purpose

---

## Stakeholders

| Role | Responsibility |
|------|---------------|
| CEO | Final decision authority |
| PM | Requirements and planning |
| Architect | Technical design |
| Developer | Implementation |

---

## Success Criteria

<!-- Define how success is measured -->

- [ ] TODO: Define success criteria

---

## Constraints

<!-- Technical, business, or resource constraints -->

- **Budget:** TBD
- **Timeline:** TBD
- **Technology:** TBD

---

## Quality Standards

| Metric | Target |
|--------|--------|
| Test Coverage | 85%+ |
| Vibecoding Index | < 40 (Green) |
| Build Time | < 60s |
| Response Time | < 100ms p95 |

---

## Related Projects

<!-- List related or dependent projects -->

- None defined

---

*Generated by EndiorBot - SDLC Framework v${project.frameworkVersion}*
`;
}
