/**
 * IDENTITY.md Generator
 *
 * Generates IDENTITY.md content for project identity.
 *
 * @module sdlc/scaffold/templates/identity-md
 * @version 1.1.0
 * @date 2026-03-05
 * @status ACTIVE - Sprint 79
 */

import type { ProjectConfig } from "../types.js";
import type { ProjectSnapshot } from "../../compliance/fix-types.js";

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate IDENTITY.md content.
 * When snapshot is provided, includes detected tech stack section.
 */
export function generateIdentityMd(project: ProjectConfig, snapshot?: ProjectSnapshot): string {
  const techStackSection = snapshot ? buildTechStackSection(snapshot) : "";

  return `# ${project.name} - Project Identity

## Core Identity

**Project:** ${project.name}
**ID:** ${project.id}
**Tier:** ${project.tier}
**Framework:** SDLC ${project.frameworkVersion}

---
${techStackSection}
## Description

${project.description || `${project.name} is a project managed with the SDLC Framework.`}

---

## Purpose

<!-- Define the core purpose of this project -->
> What problem does this project solve?

TODO: Add project purpose

---

## Stakeholders

| Role | Responsibility |
|------|---------------|
| CEO | Final decision authority |
| PM | Requirements and planning |
| Architect | Technical design |
| Developer | Implementation |

---

## Success Criteria

<!-- Define how success is measured -->

- [ ] TODO: Define success criteria

---

## Constraints

<!-- Technical, business, or resource constraints -->

- **Budget:** TBD
- **Timeline:** TBD
- **Technology:** TBD

---

## Quality Standards

| Metric | Target |
|--------|--------|
| Test Coverage | 85%+ |
| Vibecoding Index | < 40 (Green) |
| Build Time | < 60s |
| Response Time | < 100ms p95 |

---

## Related Projects

<!-- List related or dependent projects -->

- None defined

---

*Generated by EndiorBot - SDLC Framework v${project.frameworkVersion}*
`;
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Build ## Tech Stack section from detected snapshot.
 * Returns empty string if no meaningful info available.
 */
function buildTechStackSection(snapshot: ProjectSnapshot): string {
  const ts = snapshot.techStack;
  const lines: string[] = [];

  lines.push(`- **Language:** ${ts.language}`);
  if (ts.framework) lines.push(`- **Framework:** ${ts.framework}`);
  if (ts.packageManager) lines.push(`- **Package Manager:** ${ts.packageManager}`);
  if (ts.desktop) lines.push(`- **Desktop Runtime:** ${ts.desktop}`);
  if (ts.hasTypeScript) lines.push(`- **TypeScript:** Yes`);
  if (ts.hasDocker) lines.push(`- **Docker:** Yes`);
  if (ts.hasCI) lines.push(`- **CI/CD:** Yes`);

  if (lines.length === 0) return "";

  return `
## Tech Stack

${lines.join("\n")}

---
`;
}
