/**
 * Plugin Manifest Generator
 *
 * Generates .claude-plugin/plugin.json (Anthropic Base profile).
 * Sprint 151, ADR-056.
 *
 * @module sdlc/scaffold/templates/plugin-manifest
 * @version 1.0.0
 * @date 2026-05-27
 * @status ACTIVE - Sprint 151
 * @sdlc SDLC Framework 6.3.1
 */

import type { ProjectConfig } from "../types.js";
import type { ProjectSnapshot } from "../../compliance/fix-types.js";

/** Base profile plugin manifest (Anthropic-compatible, no Governed fields). */
export interface PluginManifest {
  schema_profile: "base";
  schema_version: string;
  runtime_compat: string;
  name: string;
  version: string;
  description: string;
  required_context: {
    filesystem_paths: string[];
    env_vars: string[];
    secrets_required: boolean;
  };
}

/**
 * Generate .claude-plugin/plugin.json content (Base profile).
 * Name is kebab-case normalized via project.id (already slugified).
 */
export function generatePluginManifest(
  project: ProjectConfig,
  _snapshot?: ProjectSnapshot
): string {
  const manifest: PluginManifest = {
    schema_profile: "base",
    schema_version: "0.1.0",
    runtime_compat: ">=0.1.0 <1.0.0",
    name: project.id,
    version: "0.1.0",
    description: project.description || `${project.name} — Generated by EndiorBot`,
    required_context: {
      filesystem_paths: ["repo"],
      env_vars: [],
      secrets_required: false,
    },
  };

  return JSON.stringify(manifest, null, 2) + "\n";
}

/**
 * Generate seed commands/README.md content.
 */
export function generateCommandsReadme(project: ProjectConfig): string {
  return [
    `# Commands — ${project.name}`,
    "",
    "Place your slash commands here as markdown files.",
    "",
    "Each `.md` file in this directory becomes a `/command-name` available in Claude Code.",
    "",
    "## Format",
    "",
    "```markdown",
    "---",
    "name: my-command",
    "description: What this command does",
    "---",
    "",
    "# /my-command",
    "",
    "Instructions for Claude when this command is invoked.",
    "```",
    "",
    "See [Anthropic knowledge-work-plugins](https://github.com/anthropics/knowledge-work-plugins) for examples.",
    "",
  ].join("\n");
}

/**
 * Generate seed skills/README.md content.
 */
export function generateSkillsReadme(project: ProjectConfig): string {
  return [
    `# Skills — ${project.name}`,
    "",
    "Place your skill files here. Each skill is a folder with a `SKILL.md` file:",
    "",
    "```",
    "skills/",
    "├── code-review/",
    "│   └── SKILL.md",
    "├── testing/",
    "│   └── SKILL.md",
    "└── README.md  (this file)",
    "```",
    "",
    "Skills are loaded automatically when their description matches the current task.",
    "",
    "## SKILL.md Format",
    "",
    "```markdown",
    "---",
    "name: code-review",
    "description: Review code for security, performance, and correctness",
    "---",
    "",
    "# Code Review",
    "",
    "Instructions and domain knowledge Claude draws on automatically.",
    "```",
    "",
  ].join("\n");
}
