/* ============================================================
   Endiorbot — copy / data, EN + VI
   ============================================================ */

window.EB_COPY = {
  en: {
    nav: {
      features: "Features",
      agents: "Agents",
      channels: "Channels",
      method: "Methodology",
      docs: "Docs",
      github: "GitHub",
      install: "npm install",
    },
    hero: {
      pill: "v0.1.0-beta.1 · Open Source · MIT",
      title_pre: "From",
      title_em: "30 minutes",
      title_mid: "to",
      title_em2: "30 seconds.",
      title_post: "",
      sub: "Endiorbot is a personal AI orchestration tool for solo developers shipping enterprise-scale code. 14 specialized agents, 5 channels, one process — all running on your machine.",
      install: "npx endiorbot init",
      cta_primary: "Star on GitHub",
      cta_secondary: "Read the docs",
      stats: [
        { num: "14", lbl: "Soul agents" },
        { num: "5", lbl: "Channels" },
        { num: "39", lbl: "Commands" },
        { num: "8,142+", lbl: "Tests passing" },
        { num: "MIT", lbl: "License" },
      ],
    },
    terminal: {
      title: "endior — zsh — 80×24",
      lines: [
        { t: "comment", v: "# Solo dev. Enterprise project. Tuesday, 10:42pm." },
        { t: "prompt", v: "$", c: "endiorbot @pm \"plan payment gateway sprint\"" },
        { t: "out", v: "  ✓ @pm  4 stories drafted · G1 ready · risks flagged (3)" },
        { t: "spacer" },
        { t: "prompt", v: "$", c: "endiorbot @consult \"redis vs postgres for sessions?\"" },
        { t: "out", v: "  ◇ Claude · GPT-4 · Gemini · Kimi  →  consensus in 8.4s" },
        { t: "out", v: "  ✓ @cto  Use Postgres + LISTEN/NOTIFY. ADR-018 drafted." },
        { t: "spacer" },
        { t: "prompt", v: "$", c: "endiorbot @coder --patch \"fix race in auth/refresh.ts\"" },
        { t: "out", v: "  ✓ @coder  patch ready · 1 file · 12 +/3 −  · tests pass (47)" },
        { t: "spacer" },
        { t: "comment", v: "# 18 minutes saved. Coffee still hot." },
        { t: "caret" },
      ],
    },
    sections: {
      channels: {
        eyebrow: "Channels",
        title: "Same agents,",
        title_em: "any surface.",
        lede: "Run one process. Talk to it from your terminal, browser, phone, or desktop. The 39 unified commands behave identically everywhere.",
      },
      agents: {
        eyebrow: "14 SOUL Agents",
        title: "Your personal",
        title_em: "engineering org.",
        lede: "Each agent is a SOUL template — a tier-aware persona with its own prompts, model selection, and SDLC role. Mention any of them with @, or chain several together.",
      },
      arch: {
        eyebrow: "Architecture",
        title: "Unified serve.",
        title_em: "One process.",
        lede: "Five channels feed a single message bus. Commands, agent mentions, and bridge calls are dispatched through SDLC-aware routing with PID lockfile, circuit breaker, and 60-second OTT timeouts.",
      },
      mm: {
        eyebrow: "Multi-model orchestration",
        title: "Six providers,",
        title_em: "one verdict.",
        lede: "Query Claude, GPT, Gemini, Kimi, Ollama and Groq in parallel. Endiorbot consolidates expert opinions — no more manual copy-paste between tabs.",
      },
      ba: {
        eyebrow: "Use case",
        title: "30 minutes of context-switching,",
        title_em: "compressed.",
        lede: "A real Tuesday-night moment for a solo dev: \"should I use Redis or Postgres for sessions?\"",
      },
      sdlc: {
        eyebrow: "SDLC Framework 6.3.1",
        title: "Governance for one,",
        title_em: "shaped for many.",
        lede: "Endiorbot ships with the same 7-Pillar, 10-Stage methodology used in enterprise teams — minus the bureaucracy. Quality gates G0 through G4, evidence trails, ADRs, and a Vibecoding Index built in.",
      },
      qs: {
        eyebrow: "Quickstart",
        title: "Two commands.",
        title_em: "You're talking to agents.",
      },
      sprint: {
        eyebrow: "Sprint 144 · 2026-04-27",
        title: "Shipping every week,",
        title_em: "in the open.",
      },
      oss: {
        title: "We're going OSS.",
        title_em: "Help shape what's next.",
        lede: "Endiorbot is MIT-licensed and built in public on GitHub. Star the repo, file an issue, or pick up a good-first-issue. Community feedback drives the roadmap.",
        cta_primary: "Star on GitHub",
        cta_secondary: "Browse issues",
        cta_tertiary: "Read CONTRIBUTING",
      },
      faq: { eyebrow: "FAQ", title: "Questions,", title_em: "answered." },
    },
    channels_data: [
      { name: "CLI", desc: "For terminal power users. Pipe-friendly, scriptable.", code: "endiorbot @pm …" },
      { name: "Web UI", desc: "Browser chat, runs on localhost:18790.", code: ":18790/ws" },
      { name: "Telegram", desc: "Full OTT bridge. Talk to your codebase from anywhere.", code: "@Endior_bot" },
      { name: "Zalo", desc: "Native Vietnam OTT support — first-class citizen.", code: "Bot Endior" },
      { name: "Desktop", desc: "Electron client with auto-start gateway.", code: "endiorbot.app" },
    ],
    agents_data: [
      { at: "architect", role: "Executor", tier: 1, use: "ADRs, system design, G2 gate" },
      { at: "ceo",       role: "Advisor",  tier: 1, use: "Strategy, Go/No-Go calls" },
      { at: "cso",       role: "Advisor",  tier: 1, use: "Security review, threat modeling" },
      { at: "coder",     role: "Executor", tier: 2, use: "Code generation, bug fixes" },
      { at: "reviewer",  role: "Executor", tier: 2, use: "Code review, quality checks" },
      { at: "pm",        role: "Executor", tier: 2, use: "Sprint planning, requirements" },
      { at: "tester",    role: "Executor", tier: 2, use: "Test strategy, E2E coverage" },
      { at: "devops",    role: "Executor", tier: 2, use: "CI/CD, deployment, infra" },
      { at: "fullstack", role: "Executor", tier: 2, use: "End-to-end features" },
      { at: "researcher",role: "Executor", tier: 2, use: "Technology research" },
      { at: "cto",       role: "Advisor",  tier: 2, use: "Architecture review" },
      { at: "cpo",       role: "Advisor",  tier: 2, use: "Product vision" },
      { at: "pjm",       role: "Executor", tier: 2, use: "Project tracking, velocity" },
      { at: "assistant", role: "Router",   tier: 3, use: "General queries, routing" },
    ],
    pillars: [
      { k: "01", v: "Design Thinking Foundation" },
      { k: "02", v: "10 Lifecycle Stages" },
      { k: "03", v: "Sprint Governance" },
      { k: "04", v: "4-Tier Classification" },
      { k: "05", v: "Quality Gates G0–G4" },
      { k: "06", v: "SASE Integration" },
      { k: "07", v: "Documentation Permanence" },
    ],
    gates: [
      { id: "G0", name: "Concept", desc: "Problem framed, scope defined" },
      { id: "G1", name: "Plan",    desc: "Backlog, risks, sprint shape" },
      { id: "G2", name: "Design",  desc: "ADRs locked, contracts agreed" },
      { id: "G3", name: "Build",   desc: "Code merged, tests green" },
      { id: "G4", name: "Ship",    desc: "Deployed, monitored, evidence archived" },
    ],
    sprint: {
      title: "Sprint",
      num: 144,
      meta: "2026-04-27 · 8,142+ tests passing",
      items: [
        { tag: "FEAT", t: "PID lockfile single-instance guard", d: "Use --force to take over a running instance." },
        { tag: "FEAT", t: "Provider circuit breaker", d: "Auto-trip on repeated provider failures with configurable recovery." },
        { tag: "FIX",  t: "OTT 60s hard timeout", d: "Telegram + Zalo handlers can no longer hang sessions." },
        { tag: "SHIP", t: "Desktop app (Electron)", d: "Native client with gateway auto-start on launch." },
      ],
    },
    timeline: [
      { ver: "v0.1.0β", title: "Open-source launch", desc: "MIT license, 14 agents, 5 channels, 39 commands.", now: true },
      { ver: "v0.2.0",  title: "Composio tool integration", desc: "First-class third-party tool plugins, bundled by default." },
      { ver: "v0.3.0",  title: "Hosted gateway (optional)",  desc: "Self-host stays default; managed cloud for teams that want it." },
      { ver: "v1.0.0",  title: "Stable API",                 desc: "API freeze, semver guarantees, production support tier." },
    ],
    contrib: [
      { num: "01", t: "Star the repo",       d: "Visibility helps OSS contributors find us." },
      { num: "02", t: "File issues",         d: "Bug reports, feature requests, design feedback — all welcome." },
      { num: "03", t: "Ship a SOUL",         d: "Author your own agent template. We'll review and merge." },
    ],
    faq: [
      { q: "Why not just use Claude Code directly?",
        a: "Endiorbot is the orchestrator above Claude Code. It governs which agent answers, picks the right model tier, fans out multi-model consultation, and ties results back to SDLC artefacts. Claude Code does the actual code work; Endiorbot decides what work to do." },
      { q: "Do I need an Anthropic API key?",
        a: "Yes — Anthropic is the primary provider. Google API key is recommended as a fallback. You can also wire in OpenAI, Kimi, Groq, or run Ollama locally." },
      { q: "Is this production-ready?",
        a: "It's tagged beta. APIs may change between releases. 8,142+ tests pass and it's been used daily on a ~1M LOC codebase, but no SLA — community feedback shapes the road to v1.0." },
      { q: "Why a separate Zalo channel?",
        a: "Zalo is the dominant OTT in Vietnam. Treating it as a first-class channel lets Vietnamese solo devs work with Endiorbot from the same app they already live in." },
      { q: "What's a SOUL?",
        a: "A SOUL is a template that defines an agent's persona, prompts, model tier, and allowed actions. Endiorbot ships 14, and you can author your own — they're plain Markdown." },
      { q: "Where does my code go?",
        a: "Nowhere we don't control. The gateway runs on your machine. Calls go directly from your machine to whichever LLM provider you configure. No Endiorbot-hosted servers in the loop." },
    ],
    foot: {
      tag: "Solo developer power tool. SDLC Framework 6.3.1.",
      product: { h: "Product", links: [["Features", "#features"], ["Agents", "#agents"], ["Architecture", "#arch"], ["Methodology", "#sdlc"], ["Roadmap", "#roadmap"]] },
      resources: { h: "Resources", links: [["Documentation", "#"], ["Usage Guide", "#"], ["GitHub", "#"], ["npm", "#"], ["Changelog", "#"]] },
      community: { h: "Community", links: [["Contributing", "#"], ["Issues", "#"], ["Discussions", "#"], ["Security", "#"], ["Contact", "mailto:dttai@endior.net"]] },
      copy: "MIT License · Minh-Tam-Solution & Contributors · endior.net",
    },
  },

  vi: {
    nav: {
      features: "Tính năng",
      agents: "Agent",
      channels: "Kênh",
      method: "Phương pháp",
      docs: "Tài liệu",
      github: "GitHub",
      install: "Cài đặt",
    },
    hero: {
      pill: "v0.1.0-beta.1 · Mã nguồn mở · MIT",
      title_pre: "Từ",
      title_em: "30 phút",
      title_mid: "xuống",
      title_em2: "30 giây.",
      title_post: "",
      sub: "Endiorbot là công cụ điều phối AI cá nhân dành cho lập trình viên solo đang gánh dự án quy mô doanh nghiệp. 14 agent chuyên biệt, 5 kênh, một tiến trình — chạy ngay trên máy của bạn.",
      install: "npx endiorbot init",
      cta_primary: "Gắn sao trên GitHub",
      cta_secondary: "Đọc tài liệu",
      stats: [
        { num: "14", lbl: "SOUL agent" },
        { num: "5",  lbl: "Kênh" },
        { num: "39", lbl: "Lệnh" },
        { num: "8,142+", lbl: "Test pass" },
        { num: "MIT", lbl: "Giấy phép" },
      ],
    },
    terminal: {
      title: "endior — zsh — 80×24",
      lines: [
        { t: "comment", v: "# Dev solo. Dự án enterprise. Thứ ba, 22:42." },
        { t: "prompt", v: "$", c: "endiorbot @pm \"lên kế hoạch sprint payment gateway\"" },
        { t: "out", v: "  ✓ @pm  4 story · sẵn G1 · phát hiện 3 rủi ro" },
        { t: "spacer" },
        { t: "prompt", v: "$", c: "endiorbot @consult \"redis hay postgres cho session?\"" },
        { t: "out", v: "  ◇ Claude · GPT-4 · Gemini · Kimi  →  đồng thuận trong 8.4s" },
        { t: "out", v: "  ✓ @cto  Dùng Postgres + LISTEN/NOTIFY. ADR-018 đã soạn." },
        { t: "spacer" },
        { t: "prompt", v: "$", c: "endiorbot @coder --patch \"sửa race trong auth/refresh.ts\"" },
        { t: "out", v: "  ✓ @coder  patch sẵn sàng · 1 file · 12 +/3 −  · 47 test pass" },
        { t: "spacer" },
        { t: "comment", v: "# Tiết kiệm 18 phút. Cà phê vẫn còn nóng." },
        { t: "caret" },
      ],
    },
    sections: {
      channels: {
        eyebrow: "Kênh",
        title: "Cùng một agent,",
        title_em: "khắp mọi nơi.",
        lede: "Chạy một tiến trình. Trò chuyện qua terminal, trình duyệt, điện thoại hay desktop. 39 lệnh hợp nhất hoạt động giống hệt nhau ở mọi kênh.",
      },
      agents: {
        eyebrow: "14 SOUL Agent",
        title: "Đội ngũ kỹ sư",
        title_em: "của riêng bạn.",
        lede: "Mỗi agent là một SOUL template — persona phân tier, có prompt riêng, model riêng và vai trò SDLC riêng. Gọi bằng @, hoặc kết hợp nhiều agent cùng lúc.",
      },
      arch: {
        eyebrow: "Kiến trúc",
        title: "Unified serve.",
        title_em: "Một tiến trình.",
        lede: "Năm kênh đổ về một message bus duy nhất. Lệnh, mention agent, bridge call đều được điều phối qua routing SDLC-aware kèm PID lockfile, circuit breaker, timeout 60s cho OTT.",
      },
      mm: {
        eyebrow: "Điều phối đa mô hình",
        title: "Sáu nhà cung cấp,",
        title_em: "một câu trả lời.",
        lede: "Truy vấn Claude, GPT, Gemini, Kimi, Ollama và Groq song song. Endiorbot tổng hợp ý kiến chuyên gia — không còn cảnh copy-paste giữa các tab.",
      },
      ba: {
        eyebrow: "Tình huống thực tế",
        title: "30 phút bị ngắt mạch,",
        title_em: "nén lại.",
        lede: "Một tối thứ ba có thật của dev solo: \"nên dùng Redis hay Postgres cho session?\"",
      },
      sdlc: {
        eyebrow: "SDLC Framework 6.3.1",
        title: "Quản trị cho một người,",
        title_em: "tư duy nhiều người.",
        lede: "Endiorbot đi kèm phương pháp 7 Trụ cột, 10 Giai đoạn vốn dùng cho team enterprise — bỏ đi phần quan liêu. Quality Gate G0–G4, evidence trail, ADR, Vibecoding Index có sẵn.",
      },
      qs: {
        eyebrow: "Bắt đầu nhanh",
        title: "Hai lệnh.",
        title_em: "Bạn đang nói chuyện với agent.",
      },
      sprint: {
        eyebrow: "Sprint 144 · 2026-04-27",
        title: "Ship hàng tuần,",
        title_em: "công khai.",
      },
      oss: {
        title: "Chúng tôi mở mã nguồn.",
        title_em: "Cùng định hình bước tiếp theo.",
        lede: "Endiorbot dùng giấy phép MIT và phát triển công khai trên GitHub. Gắn sao, mở issue, hoặc nhặt một good-first-issue. Cộng đồng định hướng roadmap.",
        cta_primary: "Gắn sao trên GitHub",
        cta_secondary: "Xem issue",
        cta_tertiary: "Đọc CONTRIBUTING",
      },
      faq: { eyebrow: "FAQ", title: "Câu hỏi", title_em: "thường gặp." },
    },
    channels_data: [
      { name: "CLI", desc: "Cho dân terminal. Thân thiện với pipe và script.", code: "endiorbot @pm …" },
      { name: "Web UI", desc: "Chat trên trình duyệt, chạy ở localhost:18790.", code: ":18790/ws" },
      { name: "Telegram", desc: "OTT bridge đầy đủ. Trò chuyện với codebase từ bất kỳ đâu.", code: "@Endior_bot" },
      { name: "Zalo", desc: "Hỗ trợ OTT Việt Nam — công dân hạng nhất.", code: "Bot Endior" },
      { name: "Desktop", desc: "Client Electron tự khởi động gateway.", code: "endiorbot.app" },
    ],
    agents_data: [
      { at: "architect", role: "Thực thi", tier: 1, use: "ADR, thiết kế hệ thống, G2 gate" },
      { at: "ceo",       role: "Cố vấn",   tier: 1, use: "Chiến lược, quyết định Go/No-Go" },
      { at: "cso",       role: "Cố vấn",   tier: 1, use: "Bảo mật, threat modeling" },
      { at: "coder",     role: "Thực thi", tier: 2, use: "Sinh code, sửa bug" },
      { at: "reviewer",  role: "Thực thi", tier: 2, use: "Review code, kiểm tra chất lượng" },
      { at: "pm",        role: "Thực thi", tier: 2, use: "Lên sprint, requirements" },
      { at: "tester",    role: "Thực thi", tier: 2, use: "Chiến lược test, coverage E2E" },
      { at: "devops",    role: "Thực thi", tier: 2, use: "CI/CD, deploy, hạ tầng" },
      { at: "fullstack", role: "Thực thi", tier: 2, use: "Tính năng đầu cuối" },
      { at: "researcher",role: "Thực thi", tier: 2, use: "Nghiên cứu công nghệ" },
      { at: "cto",       role: "Cố vấn",   tier: 2, use: "Review kiến trúc" },
      { at: "cpo",       role: "Cố vấn",   tier: 2, use: "Tầm nhìn sản phẩm" },
      { at: "pjm",       role: "Thực thi", tier: 2, use: "Quản trị dự án, velocity" },
      { at: "assistant", role: "Router",   tier: 3, use: "Truy vấn chung, routing" },
    ],
    pillars: [
      { k: "01", v: "Nền tảng Design Thinking" },
      { k: "02", v: "10 giai đoạn vòng đời" },
      { k: "03", v: "Quản trị Sprint" },
      { k: "04", v: "Phân loại 4 Tier" },
      { k: "05", v: "Quality Gate G0–G4" },
      { k: "06", v: "Tích hợp SASE" },
      { k: "07", v: "Tài liệu thường trực" },
    ],
    gates: [
      { id: "G0", name: "Concept", desc: "Định nghĩa vấn đề, phạm vi" },
      { id: "G1", name: "Plan",    desc: "Backlog, rủi ro, hình hài sprint" },
      { id: "G2", name: "Design",  desc: "ADR khoá, contract đã chốt" },
      { id: "G3", name: "Build",   desc: "Code merge, test xanh" },
      { id: "G4", name: "Ship",    desc: "Đã deploy, monitor, evidence lưu" },
    ],
    sprint: {
      title: "Sprint",
      num: 144,
      meta: "2026-04-27 · 8,142+ test pass",
      items: [
        { tag: "FEAT", t: "PID lockfile chống chạy nhiều instance", d: "Dùng --force để giành quyền instance đang chạy." },
        { tag: "FEAT", t: "Circuit breaker cho provider", d: "Tự ngắt khi provider lỗi liên tục, recovery tuỳ chỉnh." },
        { tag: "FIX",  t: "OTT timeout cứng 60s", d: "Handler Telegram + Zalo không còn treo session." },
        { tag: "SHIP", t: "Ứng dụng desktop (Electron)", d: "Client native, gateway tự khởi động khi mở app." },
      ],
    },
    timeline: [
      { ver: "v0.1.0β", title: "Ra mắt mã nguồn mở", desc: "Giấy phép MIT, 14 agent, 5 kênh, 39 lệnh.", now: true },
      { ver: "v0.2.0",  title: "Tích hợp Composio", desc: "Plugin tool bên thứ ba, đóng gói sẵn." },
      { ver: "v0.3.0",  title: "Hosted gateway (tuỳ chọn)", desc: "Self-host vẫn mặc định; cloud quản lý cho team cần." },
      { ver: "v1.0.0",  title: "API ổn định", desc: "Đóng băng API, semver, hỗ trợ production." },
    ],
    contrib: [
      { num: "01", t: "Gắn sao repo",   d: "Giúp dự án hiển thị tới cộng đồng OSS." },
      { num: "02", t: "Mở issue",       d: "Báo bug, đề xuất tính năng, góp ý thiết kế — đều hoan nghênh." },
      { num: "03", t: "Đóng góp SOUL",  d: "Tự viết một agent template. Chúng tôi sẽ review và merge." },
    ],
    faq: [
      { q: "Sao không dùng thẳng Claude Code?",
        a: "Endiorbot là lớp điều phối phía trên Claude Code. Nó quyết định agent nào trả lời, chọn tier model, gửi truy vấn đa mô hình, rồi gắn kết quả về artefact SDLC. Claude Code làm code; Endiorbot quyết định việc nào cần làm." },
      { q: "Có cần API key Anthropic không?",
        a: "Có — Anthropic là provider chính. Khuyến nghị thêm Google API làm fallback. Bạn cũng có thể nối OpenAI, Kimi, Groq, hoặc Ollama chạy local." },
      { q: "Đã production-ready chưa?",
        a: "Đang gắn nhãn beta. API có thể đổi giữa các bản. 8,142+ test pass và đã dùng hằng ngày trên codebase ~1M LOC, nhưng chưa có SLA — phản hồi cộng đồng định hình lộ trình tới v1.0." },
      { q: "Sao có kênh Zalo riêng?",
        a: "Zalo là OTT phổ biến nhất tại Việt Nam. Đưa Zalo thành kênh hạng nhất giúp dev solo Việt làm việc với Endiorbot ngay trong app họ vốn đã dùng." },
      { q: "SOUL là gì?",
        a: "SOUL là template định nghĩa persona, prompt, model tier và hành động cho phép của agent. Endiorbot ship 14 SOUL, bạn có thể tự viết — đều là Markdown thuần." },
      { q: "Code của tôi đi đâu?",
        a: "Không qua server nào của chúng tôi. Gateway chạy trên máy bạn. Yêu cầu đi thẳng từ máy bạn tới LLM provider được cấu hình. Không có máy chủ Endiorbot ở giữa." },
    ],
    foot: {
      tag: "Công cụ AI cho dev solo. SDLC Framework 6.3.1.",
      product:   { h: "Sản phẩm",  links: [["Tính năng", "#features"], ["Agent", "#agents"], ["Kiến trúc", "#arch"], ["Phương pháp", "#sdlc"], ["Roadmap", "#roadmap"]] },
      resources: { h: "Tài nguyên",links: [["Tài liệu", "#"], ["Hướng dẫn", "#"], ["GitHub", "#"], ["npm", "#"], ["Changelog", "#"]] },
      community: { h: "Cộng đồng", links: [["Đóng góp", "#"], ["Issue", "#"], ["Thảo luận", "#"], ["Bảo mật", "#"], ["Liên hệ", "mailto:dttai@endior.net"]] },
      copy: "Giấy phép MIT · Minh-Tam-Solution & cộng đồng · endior.net",
    },
  },
};
