/**
 * L2 Content Checker Tests
 *
 * Unit tests for content quality validation (BUG-011 fix).
 *
 * @module tests/sdlc/compliance/content-checker
 * @version 1.0.0
 * @date 2026-03-03
 * @status ACTIVE - Sprint 73
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import {
  isPlaceholderLine,
  countPlaceholders,
  countContentLines,
  checkStageContent,
  checkL2Compliance,
  STAGE_CONTENT_REQUIREMENTS,
} from "../../../src/sdlc/compliance/content-checker.js";

// ============================================================================
// Placeholder Detection
// ============================================================================

describe("isPlaceholderLine", () => {
  it("should detect TODO: Add patterns", () => {
    expect(isPlaceholderLine("- [ ] TODO: Add test artifacts")).toBe(true);
    expect(isPlaceholderLine("TODO: Add planning artifacts")).toBe(true);
  });

  it("should detect TBD markers", () => {
    expect(isPlaceholderLine("| TBD | Pending | TBD |")).toBe(true);
  });

  it("should detect HTML placeholder comments", () => {
    expect(isPlaceholderLine("<!-- Add stage-specific documentation here -->")).toBe(true);
  });

  it("should detect Generated by EndiorBot marker", () => {
    expect(isPlaceholderLine("*Generated by EndiorBot - SDLC Framework v6.1.1*")).toBe(true);
  });

  it("should NOT flag real content", () => {
    expect(isPlaceholderLine("## Problem Statement")).toBe(false);
    expect(isPlaceholderLine("The system shall provide authentication")).toBe(false);
    expect(isPlaceholderLine("- User login with email/password")).toBe(false);
  });
});

describe("countPlaceholders", () => {
  it("should count placeholder lines in template content", () => {
    const template = [
      "# 05-test - Test",
      "",
      "## Contents",
      "<!-- Add stage-specific documentation here -->",
      "- [ ] TODO: Add test artifacts",
      "",
      "| TBD | Pending | TBD |",
      "",
      "*Generated by EndiorBot - SDLC Framework v6.1.1*",
    ].join("\n");

    const placeholders = countPlaceholders(template);
    expect(placeholders.length).toBe(4);
  });

  it("should return empty for real content", () => {
    const content = [
      "# Problem Statement",
      "",
      "## Overview",
      "The application needs to handle user authentication.",
      "",
      "## Requirements",
      "- Login with email/password",
      "- OAuth2 integration",
    ].join("\n");

    expect(countPlaceholders(content)).toEqual([]);
  });
});

// ============================================================================
// Content Line Counting
// ============================================================================

describe("countContentLines", () => {
  it("should count non-empty, non-placeholder lines", () => {
    const content = [
      "# Title",
      "",
      "Some real content here.",
      "More content.",
      "---",
      "- [ ] TODO: Add artifacts",
      "Final line.",
    ].join("\n");

    // "# Title" (1) + "Some real content" (2) + "More content" (3) + "Final line" (4)
    // Excludes: empty, ---, TODO placeholder
    expect(countContentLines(content)).toBe(4);
  });

  it("should return 0 for empty content", () => {
    expect(countContentLines("")).toBe(0);
    expect(countContentLines("\n\n\n")).toBe(0);
  });

  it("should return 0 for placeholder-only content", () => {
    const content = [
      "---",
      "- [ ] TODO: Add artifacts",
      "*Generated by EndiorBot - SDLC Framework v6.1.1*",
      "---",
    ].join("\n");

    expect(countContentLines(content)).toBe(0);
  });
});

// ============================================================================
// Stage Content Requirements
// ============================================================================

describe("STAGE_CONTENT_REQUIREMENTS", () => {
  it("should have requirements for all standard stages", () => {
    expect(STAGE_CONTENT_REQUIREMENTS["00-foundation"]).toBeDefined();
    expect(STAGE_CONTENT_REQUIREMENTS["01-planning"]).toBeDefined();
    expect(STAGE_CONTENT_REQUIREMENTS["02-design"]).toBeDefined();
    expect(STAGE_CONTENT_REQUIREMENTS["04-build"]).toBeDefined();
    expect(STAGE_CONTENT_REQUIREMENTS["05-test"]).toBeDefined();
  });

  it("should require problem-statement.md for 00-foundation", () => {
    const req = STAGE_CONTENT_REQUIREMENTS["00-foundation"];
    expect(req.requiredArtifacts).toContain("problem-statement.md");
  });

  it("should require requirements.md for 01-planning", () => {
    const req = STAGE_CONTENT_REQUIREMENTS["01-planning"];
    expect(req.requiredArtifacts).toContain("requirements.md");
  });
});

// ============================================================================
// Stage Content Check (with temp dirs)
// ============================================================================

let tempDir: string;

beforeEach(() => {
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "endiorbot-l2-test-"));
});

afterEach(() => {
  if (tempDir && fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

describe("checkStageContent", () => {
  it("should detect placeholder-only stage (BUG-011 scenario)", () => {
    // Create a stage directory with only a template README
    const stagePath = path.join(tempDir, "docs", "05-test");
    fs.mkdirSync(stagePath, { recursive: true });
    fs.writeFileSync(
      path.join(stagePath, "README.md"),
      [
        "# 05-test - Test",
        "",
        "## Contents",
        "<!-- Add stage-specific documentation here -->",
        "- [ ] TODO: Add test artifacts",
        "",
        "| TBD | Pending | TBD |",
        "",
        "*Generated by EndiorBot - SDLC Framework v6.1.1*",
      ].join("\n"),
    );

    const result = checkStageContent(tempDir, "05-test");
    expect(result.hasRealContent).toBe(false);
    expect(result.placeholdersFound.length).toBeGreaterThan(0);
    expect(result.contentScore).toBeLessThan(50);
  });

  it("should detect stage with real content", () => {
    const stagePath = path.join(tempDir, "docs", "00-foundation");
    fs.mkdirSync(stagePath, { recursive: true });

    // Create a real problem-statement.md
    const lines: string[] = [];
    lines.push("# Problem Statement");
    lines.push("");
    lines.push("## Overview");
    for (let i = 0; i < 30; i++) {
      lines.push(`Real content line ${i + 1} describing the problem.`);
    }
    fs.writeFileSync(path.join(stagePath, "problem-statement.md"), lines.join("\n"));

    // Create business-case.md
    const bLines: string[] = [];
    bLines.push("# Business Case");
    bLines.push("");
    for (let i = 0; i < 20; i++) {
      bLines.push(`Business justification line ${i + 1}.`);
    }
    fs.writeFileSync(path.join(stagePath, "business-case.md"), bLines.join("\n"));

    const result = checkStageContent(tempDir, "00-foundation");
    expect(result.hasRealContent).toBe(true);
    expect(result.placeholdersFound.length).toBe(0);
    expect(result.contentScore).toBeGreaterThanOrEqual(75);
    expect(result.artifactsFound).toContain("problem-statement.md");
    expect(result.artifactsFound).toContain("business-case.md");
  });

  it("should handle non-existent stage directory", () => {
    const result = checkStageContent(tempDir, "99-nonexistent");
    expect(result.hasRealContent).toBe(false);
    expect(result.contentScore).toBe(0);
  });
});

// ============================================================================
// Full L2 Compliance Check
// ============================================================================

describe("checkL2Compliance", () => {
  it("should score low for placeholder-only project (BUG-011 verification)", () => {
    // Create standard stage structure with all placeholders
    const stages = ["00-foundation", "01-planning", "02-design", "04-build", "05-test"];
    for (const stage of stages) {
      const stagePath = path.join(tempDir, "docs", stage);
      fs.mkdirSync(stagePath, { recursive: true });
      fs.writeFileSync(
        path.join(stagePath, "README.md"),
        [
          `# ${stage}`,
          "<!-- Add stage-specific documentation here -->",
          "- [ ] TODO: Add artifacts",
          "| TBD | Pending | TBD |",
          "*Generated by EndiorBot*",
        ].join("\n"),
      );
    }

    const result = checkL2Compliance(tempDir, stages, "STANDARD");
    expect(result.score).toBeLessThan(50);
    expect(result.issues.length).toBeGreaterThan(0);
    expect(result.issues.some((i) => i.type === "placeholder")).toBe(true);
  });

  it("should score high for project with real content", () => {
    // Create 00-foundation with real content
    const foundationPath = path.join(tempDir, "docs", "00-foundation");
    fs.mkdirSync(foundationPath, { recursive: true });

    const lines: string[] = ["# Problem Statement", ""];
    for (let i = 0; i < 30; i++) lines.push(`Content line ${i + 1}.`);
    fs.writeFileSync(path.join(foundationPath, "problem-statement.md"), lines.join("\n"));
    fs.writeFileSync(path.join(foundationPath, "business-case.md"), lines.join("\n"));

    const result = checkL2Compliance(tempDir, ["00-foundation"], "STANDARD");
    expect(result.score).toBe(100);
    expect(result.passedChecks).toBe(1);
  });
});
